FROM node:5

WORKDIR /test

COPY package.json package.json
COPY test.sh test.sh
COPY codecept.conf.js codecept.conf.js
COPY config.js config.js
COPY mock-postcode.js mock-postcode.js
COPY apps apps/

RUN npm --loglevel warn install --ignore-scripts

CMD /test/test.sh
